-- MySQL Script generated by MySQL Workbench
-- Sat Jan 13 23:29:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema individualProjectStickalster
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema individualProjectStickalster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `individualProjectStickalster` DEFAULT CHARACTER SET utf8 ;
USE `individualProjectStickalster` ;

-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`Garn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`Garn` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nameManuf` VARCHAR(45) NULL,
  `material` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`Mottagare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`Mottagare` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `namn` VARCHAR(45) NOT NULL,
  `kontakt` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`Item` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `modellTyp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`Alster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`Alster` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Mottagare_ID` INT NOT NULL,
  `teknik` VARCHAR(45) NULL,
  `feature` VARCHAR(45) NULL,
  `sticka` INT NULL,
  `pris` INT NULL,
  PRIMARY KEY (`ID`, `Mottagare_ID`),
  INDEX `fk_Alster_Mottagare1_idx` (`Mottagare_ID` ASC),
  CONSTRAINT `fk_Alster_Mottagare1`
    FOREIGN KEY (`Mottagare_ID`)
    REFERENCES `individualProjectStickalster`.`Mottagare` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`colour` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `colour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`Garn_has_colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`Garn_has_colour` (
  `Garn_ID` INT NOT NULL,
  `colour_ID` INT NOT NULL,
  PRIMARY KEY (`Garn_ID`, `colour_ID`),
  INDEX `fk_Garn_has_colour_colour1_idx` (`colour_ID` ASC),
  INDEX `fk_Garn_has_colour_Garn1_idx` (`Garn_ID` ASC),
  CONSTRAINT `fk_Garn_has_colour_Garn1`
    FOREIGN KEY (`Garn_ID`)
    REFERENCES `individualProjectStickalster`.`Garn` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Garn_has_colour_colour1`
    FOREIGN KEY (`colour_ID`)
    REFERENCES `individualProjectStickalster`.`colour` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`Alster_has_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`Alster_has_Item` (
  `Alster_ID` INT NOT NULL,
  `Alster_Mottagare_ID` INT NOT NULL,
  `Item_ID` INT NOT NULL,
  PRIMARY KEY (`Alster_ID`, `Alster_Mottagare_ID`, `Item_ID`),
  INDEX `fk_Alster_has_Item_Item1_idx` (`Item_ID` ASC),
  INDEX `fk_Alster_has_Item_Alster1_idx` (`Alster_ID` ASC, `Alster_Mottagare_ID` ASC),
  CONSTRAINT `fk_Alster_has_Item_Alster1`
    FOREIGN KEY (`Alster_ID` , `Alster_Mottagare_ID`)
    REFERENCES `individualProjectStickalster`.`Alster` (`ID` , `Mottagare_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alster_has_Item_Item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `individualProjectStickalster`.`Item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `individualProjectStickalster`.`Alster_has_Garn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `individualProjectStickalster`.`Alster_has_Garn` (
  `Alster_ID` INT NOT NULL,
  `Alster_Mottagare_ID` INT NOT NULL,
  `Garn_ID` INT NOT NULL,
  PRIMARY KEY (`Alster_ID`, `Alster_Mottagare_ID`, `Garn_ID`),
  INDEX `fk_Alster_has_Garn_Garn1_idx` (`Garn_ID` ASC),
  INDEX `fk_Alster_has_Garn_Alster1_idx` (`Alster_ID` ASC, `Alster_Mottagare_ID` ASC),
  CONSTRAINT `fk_Alster_has_Garn_Alster1`
    FOREIGN KEY (`Alster_ID` , `Alster_Mottagare_ID`)
    REFERENCES `individualProjectStickalster`.`Alster` (`ID` , `Mottagare_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alster_has_Garn_Garn1`
    FOREIGN KEY (`Garn_ID`)
    REFERENCES `individualProjectStickalster`.`Garn` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
